channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - conda-forge::nodejs=18
  - conda-forge::git
  - conda-forge::gcc
  - conda-forge::pip
  - conda-forge::setuptools
  - conda-forge::jupyterlab
  - pip:
      - "cybershuttle_provisioners @ git+https://github.com/cyber-shuttle/cybershuttle-notebook-gateway.git@dev#subdirectory=cybershuttle_provisioners"
      - "cybershuttle_nbplugin @ git+https://github.com/cyber-shuttle/cybershuttle-notebook-gateway.git@dev#subdirectory=cybershuttle_nbplugin"
