channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.10
  - conda-forge::jupyterlab
  - conda-forge::jupyter_kernel_gateway
  - conda-forge::pip
  - conda-forge::setuptools
  - pip:
      # source packages
      - "-e cybershuttle_provisioners/"
      - "-e cybershuttle_gateway/"
