# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: yasith@cs.odu.edu
author_name: Yasith Jayawardana
data_format: string
file_extension: ''
has_binder: false
has_settings: true
kind: server
labextension_name: cybershuttle_nbplugin
mimetype: ''
mimetype_name: ''
project_short_description: Notebook Extension for Running Remote Kernels via Cybershuttle
python_name: cybershuttle_nbplugin
repository: https://github.com/cyber-shuttle/cybershuttle-notebook-gateway
test: false
viewer_name: ''

